name: RSS to Telegram

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  rss:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Check RSS
        run: |
          FEED="https://rss.app/feeds/c3Hr9f9I5GIxbAJQ.xml"

          ITEM=$(curl -s "$FEED" | awk '/<item>/,/<\/item>/' | head -n 20)
          TITLE=$(echo "$ITEM" | grep "<title>" | head -1 | sed 's/.*<title>//;s/<\/title>.*//')
          LINK=$(echo "$ITEM" | grep "<link>" | head -1 | sed 's/.*<link>//;s/<\/link>.*//')

          if [ -f last.txt ]; then
            LAST=$(cat last.txt)
          else
            LAST=""
          fi

          if [ "$LINK" != "$LAST" ]; then
            curl -s -X POST "https://api.telegram.org/botTU_TOKEN/sendMessage" \
              -d chat_id=6436305990 \
              TITLE="DM SETTER"
            --data-urlencode "text=${TITLE} ${LINK}"

            echo "$LINK" > last.txt

            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add last.txt
